CREATE PROCEDURE SP_INSERT_USER
(@US_NAME VARCHAR(50),
@US_PASS VARCHAR(50),
@US_FULLNAME VARCHAR(50),
@PER_ID int
)


AS
INSERT INTO tbl_Users (Us_Name,Us_Passowrd,Us_FUll_Name,Per_ID) VALUES(@US_NAME,@US_PASS,@US_FUllNAME,@PER_ID)

RETURN