CREATE PROCEDURE SP_SUPPLIERSEARCH 
@SEARCH  VARCHAR(50)

AS
SELECT S.Su_ID ' SUPPLIER ID ' ,S.Su_Name 'SUPPLIER NAME',  S.Su_Mobile 'SUPPLIER MOBILE' FROM tbl_Suppliers S

WHERE CONVERT(VARCHAR,S.Su_ID)+S.Su_Name+S.Su_Mobile LIKE '%' +@SEARCH +'%'
RETURN