CREATE PROCEDURE SP_SELECTSEARCHACTIVEMATERIAL

@SEARCH VARCHAR(50)
AS
SELECT AM.Am_ID AS 'ACTIVE MATERIAL ID ',
AM.Am_name 'ACTIVE MATERIAL NAME ' ,
AM.Am_Desecription ' DESICRIPTION '
 FROM  tbl_activeMaterial AM
 WHERE 
 CONVERT(VARCHAR ,AM.AM_ID ) +  AM.Am_name +  AM.Am_Desecription LIKE '%'+@SEARCH +'%'

RETURN