CREATE PROCEDURE SP_ACTIVEMATERIALUPDATE
@ACI_ID INT ,@AC_NAME VARCHAR(50),@AC_DES varchar(MAX)
AS
UPDATE tbl_activeMaterial SET  Am_name=@AC_NAME ,Am_Desecription =@AC_DES WHERE Am_ID =@ACI_ID 
RETURN