CREATE PROCEDURE SP_SEARCHSCIENTIFICNAME
@SEARCH VARCHAR(50)

AS
SELECT sn_ID AS 'SCIENTIFIC NAME ID '  ,
sn_Name AS ' SCIENTIFIC NAME '  FROM tbl_sceintificName
 WHERE 
 CONVERT (VARCHAR ,sn_ID) + sn_Name LIKE '%' +  @SEARCH +'%'
RETURN